import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    /**
     * [activitystarter website](http://marcinmoskala.com/ActivityStarter/) */
    const val activitystarter: String =
            "com.github.MarcinMoskala.ActivityStarter:activitystarter:" + Versions.activitystarter

    /**
     * [activitystarter-compiler website](http://marcinmoskala.com/ActivityStarter/) */
    const val activitystarter_compiler: String =
            "com.github.MarcinMoskala.ActivityStarter:activitystarter-compiler:" + Versions.activitystarter_compiler

    /**
     * [activitystarter-kotlin website](http://marcinmoskala.com/ActivityStarter/) */
    const val activitystarter_kotlin: String =
            "com.github.MarcinMoskala.ActivityStarter:activitystarter-kotlin:" + Versions.activitystarter_kotlin

    /**
     * [anko-coroutines website](https://github.com/JetBrains/anko) */
    const val anko_coroutines: String =
            "org.jetbrains.anko:anko-coroutines:" + Versions.anko_coroutines

    /**
     * [appcompat-v7 website](http://developer.android.com/tools/extras/support-library.html) */
    const val appcompat_v7: String = "com.android.support:appcompat-v7:" + Versions.appcompat_v7

    const val codeview: String = "com.github.tiagohm:CodeView:" + Versions.codeview

    /**
     * [wearable website](https://developer.android.com/wear) */
    const val com_google_android_wearable_wearable: String =
            "com.google.android.support:wearable:" + Versions.com_google_android_wearable_wearable

    /**
     * [controlsfx website](http://www.controlsfx.org/) */
    const val controlsfx: String = "org.controlsfx:controlsfx:" + Versions.controlsfx

    /**
     * [converter-gson website](https://github.com/square/retrofit/) */
    const val converter_gson: String =
            "com.squareup.retrofit2:converter-gson:" + Versions.converter_gson

    /**
     * [converter-scalars website](https://github.com/square/retrofit/) */
    const val converter_scalars: String =
            "com.squareup.retrofit2:converter-scalars:" + Versions.converter_scalars

    const val crashlytics: String =
            "com.crashlytics.sdk.android:crashlytics:" + Versions.crashlytics

    /**
     * [design website](http://developer.android.com/tools/extras/support-library.html) */
    const val design: String = "com.android.support:design:" + Versions.design

    /**
     * [espresso-contrib website](https://developer.android.com/testing) */
    const val espresso_contrib: String =
            "com.android.support.test.espresso:espresso-contrib:" + Versions.espresso_contrib

    /**
     * [espresso-core website](https://developer.android.com/testing) */
    const val espresso_core: String =
            "com.android.support.test.espresso:espresso-core:" + Versions.espresso_core

    /**
     * [espresso-intents website](https://developer.android.com/testing) */
    const val espresso_intents: String =
            "com.android.support.test.espresso:espresso-intents:" + Versions.espresso_intents

    const val firebase_core: String = "com.google.firebase:firebase-core:" + Versions.firebase_core

    const val firebase_messaging: String =
            "com.google.firebase:firebase-messaging:" + Versions.firebase_messaging

    /**
     * [glide website](https://github.com/bumptech/glide) */
    const val glide: String = "com.github.bumptech.glide:glide:" + Versions.glide

    /**
     * [google-services website](http://tools.android.com/) */
    const val google_services: String = "com.google.gms:google-services:" + Versions.google_services

    const val gradle_node_plugin: String =
            "com.moowork.gradle:gradle-node-plugin:" + Versions.gradle_node_plugin

    /**
     * [gson website](https://github.com/google/gson) */
    const val gson: String = "com.google.code.gson:gson:" + Versions.gson

    /**
     * [HikariCP website](https://github.com/brettwooldridge/HikariCP) */
    const val hikaricp: String = "com.zaxxer:HikariCP:" + Versions.hikaricp

    /**
     * [gradle website](https://developer.android.com/studio) */
    const val io_fabric_tools_gradle: String =
            "com.android.tools.build:gradle:" + Versions.io_fabric_tools_gradle

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    /**
     * [joda-time website](http://www.joda.org/joda-time/) */
    const val joda_time: String = "joda-time:joda-time:" + Versions.joda_time

    /**
     * [junit website](http://junit.org) */
    const val junit: String = "junit:junit:" + Versions.junit

    /**
     * [kotlin-android-extensions website](https://kotlinlang.org/) */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.kotlin_android_extensions

    /**
     * [kotlin-android-extensions-runtime website](https://kotlinlang.org/) */
    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" + Versions.kotlin_android_extensions_runtime

    /**
     * [kotlin-annotation-processing-gradle website](https://kotlinlang.org/) */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" + Versions.kotlin_annotation_processing_gradle

    const val kotlin_frontend_plugin: String =
            "org.jetbrains.kotlin:kotlin-frontend-plugin:" + Versions.kotlin_frontend_plugin

    /**
     * [kotlin-gradle-plugin website](https://kotlinlang.org/) */
    const val kotlin_gradle_plugin: String =
            "org.jetbrains.kotlin:kotlin-gradle-plugin:" + Versions.kotlin_gradle_plugin

    const val kotlin_native_gradle_plugin: String =
            "org.jetbrains.kotlin:kotlin-native-gradle-plugin:" + Versions.kotlin_native_gradle_plugin

    const val kotlin_react: String = "org.jetbrains:kotlin-react:" + Versions.kotlin_react

    const val kotlin_react_dom: String =
            "org.jetbrains:kotlin-react-dom:" + Versions.kotlin_react_dom

    const val kotlin_react_router_dom: String =
            "org.jetbrains:kotlin-react-router-dom:" + Versions.kotlin_react_router_dom

    /**
     * [kotlin-scripting-compiler-embeddable website](https://kotlinlang.org/) */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" + Versions.kotlin_scripting_compiler_embeddable

    /**
     * [kotlin-stdlib-common website](https://kotlinlang.org/) */
    const val kotlin_stdlib_common: String =
            "org.jetbrains.kotlin:kotlin-stdlib-common:" + Versions.kotlin_stdlib_common

    /**
     * [kotlin-stdlib-jdk7 website](https://kotlinlang.org/) */
    const val kotlin_stdlib_jdk7: String =
            "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" + Versions.kotlin_stdlib_jdk7

    /**
     * [kotlin-stdlib-jdk8 website](https://kotlinlang.org/) */
    const val kotlin_stdlib_jdk8: String =
            "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" + Versions.kotlin_stdlib_jdk8

    /**
     * [kotlin-stdlib-js website](https://kotlinlang.org/) */
    const val kotlin_stdlib_js: String =
            "org.jetbrains.kotlin:kotlin-stdlib-js:" + Versions.kotlin_stdlib_js

    /**
     * [kotlin-test website](https://kotlinlang.org/) */
    const val kotlin_test: String = "org.jetbrains.kotlin:kotlin-test:" + Versions.kotlin_test

    /**
     * [kotlin-test-annotations-common website](https://kotlinlang.org/) */
    const val kotlin_test_annotations_common: String =
            "org.jetbrains.kotlin:kotlin-test-annotations-common:" + Versions.kotlin_test_annotations_common

    /**
     * [kotlin-test-common website](https://kotlinlang.org/) */
    const val kotlin_test_common: String =
            "org.jetbrains.kotlin:kotlin-test-common:" + Versions.kotlin_test_common

    /**
     * [kotlin-test-js website](https://kotlinlang.org/) */
    const val kotlin_test_js: String =
            "org.jetbrains.kotlin:kotlin-test-js:" + Versions.kotlin_test_js

    /**
     * [kotlin-test-junit website](https://kotlinlang.org/) */
    const val kotlin_test_junit: String =
            "org.jetbrains.kotlin:kotlin-test-junit:" + Versions.kotlin_test_junit

    const val kotlinandroidviewbindings: String =
            "com.github.MarcinMoskala:KotlinAndroidViewBindings:" + Versions.kotlinandroidviewbindings

    /**
     * [kotlinx-coroutines-core website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:" + Versions.kotlinx_coroutines_core

    /**
     * [kotlinx-coroutines-core-js website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_core_js: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core-js:" + Versions.kotlinx_coroutines_core_js

    const val kotlinx_coroutines_core_native: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core-native:" + Versions.kotlinx_coroutines_core_native

    /**
     * [kotlinx-coroutines-javafx website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_javafx: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-javafx:" + Versions.kotlinx_coroutines_javafx

    const val kotlinx_gradle_serialization_plugin: String =
            "org.jetbrains.kotlinx:kotlinx-gradle-serialization-plugin:" + Versions.kotlinx_gradle_serialization_plugin

    /**
     * [kotlinx-html-js website](https://github.com/Kotlin/kotlinx.html) */
    const val kotlinx_html_js: String =
            "org.jetbrains.kotlinx:kotlinx-html-js:" + Versions.kotlinx_html_js

    const val kotlinx_serialization_runtime: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-runtime:" + Versions.kotlinx_serialization_runtime

    const val kotlinx_serialization_runtime_js: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-runtime-js:" + Versions.kotlinx_serialization_runtime_js

    const val ktor_gson: String = "io.ktor:ktor-gson:" + Versions.ktor_gson

    const val ktor_server_netty: String = "io.ktor:ktor-server-netty:" + Versions.ktor_server_netty

    /**
     * [lint-gradle website](https://developer.android.com/studio) */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * [logback-classic website](http://logback.qos.ch) */
    const val logback_classic: String = "ch.qos.logback:logback-classic:" + Versions.logback_classic

    /**
     * [logging-interceptor website](https://github.com/square/okhttp) */
    const val logging_interceptor: String =
            "com.squareup.okhttp3:logging-interceptor:" + Versions.logging_interceptor

    /**
     * [mockk website](http://mockk.io) */
    const val mockk: String = "io.mockk:mockk:" + Versions.mockk

    const val multidex: String = "com.android.support:multidex:" + Versions.multidex

    const val multidex_instrumentation: String =
            "com.android.support:multidex-instrumentation:" + Versions.multidex_instrumentation

    /**
     * [okhttp website](https://github.com/square/okhttp) */
    const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.okhttp

    const val preferenceholder: String =
            "com.marcinmoskala.PreferenceHolder:preferenceholder:" + Versions.preferenceholder

    const val preferenceholder_gson_serializer: String =
            "com.marcinmoskala.PreferenceHolder:preferenceholder-gson-serializer:" + Versions.preferenceholder_gson_serializer

    /**
     * [recyclerview-v7 website](http://developer.android.com/tools/extras/support-library.html) */
    const val recyclerview_v7: String =
            "com.android.support:recyclerview-v7:" + Versions.recyclerview_v7

    /**
     * [retrofit website](https://github.com/square/retrofit/) */
    const val retrofit: String = "com.squareup.retrofit2:retrofit:" + Versions.retrofit

    /**
     * [retrofit2-kotlin-coroutines-experimental-adapter website](https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter/) */
    const val retrofit2_kotlin_coroutines_experimental_adapter: String =
            "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-experimental-adapter:" + Versions.retrofit2_kotlin_coroutines_experimental_adapter

    /**
     * [rome website](http://rometools.com) */
    const val rome: String = "com.rometools:rome:" + Versions.rome

    /**
     * [sendgrid-java website](https://github.com/sendgrid/sendgrid-java) */
    const val sendgrid_java: String = "com.sendgrid:sendgrid-java:" + Versions.sendgrid_java

    const val shadow: String = "com.github.jengelman.gradle.plugins:shadow:" + Versions.shadow

    const val squash: String = "org.jetbrains.squash:squash:" + Versions.squash

    const val squash_h2: String = "org.jetbrains.squash:squash-h2:" + Versions.squash_h2

    const val squash_postgres: String =
            "org.jetbrains.squash:squash-postgres:" + Versions.squash_postgres

    /**
     * [tornadofx website](https://github.com/edvin/tornadofx) */
    const val tornadofx: String = "no.tornado:tornadofx:" + Versions.tornadofx

    const val traynotification: String =
            "com.github.PlusHaze:TrayNotification:" + Versions.traynotification

    /**
     * [wear website](http://developer.android.com/tools/extras/support-library.html) */
    const val wear: String = "com.android.support:wear:" + Versions.wear

    object Versions {
        const val activitystarter: String = "1.12-beta-2" // up-to-date

        const val activitystarter_compiler: String = "1.12-beta-2" // up-to-date

        const val activitystarter_kotlin: String = "1.12-beta-2" // up-to-date

        const val anko_coroutines: String = "0.10.1" // available: milestone=0.10.6

        const val appcompat_v7: String = "27.0.1" // available: milestone=28.0.0

        const val codeview: String = "0.4.0" // up-to-date

        const val com_google_android_wearable_wearable: String =
                "2.1.0" // available: milestone=2.3.0

        const val controlsfx: String = "8.40.14" // available: milestone=9.0.0

        const val converter_gson: String = "2.3.0" // available: milestone=2.4.0

        const val converter_scalars: String = "2.3.0" // available: milestone=2.4.0

        const val crashlytics: String = "2.9.2" // available: milestone=2.9.5

        const val design: String = "27.0.1" // available: milestone=28.0.0

        const val espresso_contrib: String = "3.0.1" // available: milestone=3.0.2

        const val espresso_core: String = "3.0.1" // available: milestone=3.0.2

        const val espresso_intents: String = "3.0.1" // available: milestone=3.0.2

        const val firebase_core: String = "11.6.2" // available: milestone=16.0.4

        const val firebase_messaging: String = "11.6.2" // available: milestone=17.3.3

        const val glide: String = "3.7.0" // available: milestone=4.8.0

        const val google_services: String = "3.1.1" // available: milestone=4.1.0

        const val gradle_node_plugin: String = "1.2.0" // up-to-date

        const val gson: String = "2.8.2" // available: milestone=2.8.5

        const val hikaricp: String = "2.7.2" // available: milestone=3.2.0

        const val io_fabric_tools_gradle: String = "3.1.4" // available: milestone=3.3.0-alpha13

        const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
                "0.2.1" // up-to-date

        const val joda_time: String = "2.9.9" // available: milestone=2.10

        const val junit: String = "4.12" // up-to-date

        const val kotlin_android_extensions: String =
                "1.2.60" // available: milestone=1.3.20-dev-671

        const val kotlin_android_extensions_runtime: String =
                "1.2.60" // available: milestone=1.3.20-dev-671

        const val kotlin_annotation_processing_gradle: String =
                "1.2.60" // available: milestone=1.3.20-dev-671

        const val kotlin_frontend_plugin: String = "0.0.32" // available: milestone=0.0.37

        const val kotlin_gradle_plugin: String = "1.2.60" // available: milestone=1.3.20-dev-671

        const val kotlin_native_gradle_plugin: String = "0.8.1" // available: milestone=1.3.0-rc-131

        const val kotlin_react: String =
                "16.4.2-pre.38-kotlin-1.2.60" // available: milestone=16.5.0-pre.54-kotlin-1.2.70

        const val kotlin_react_dom: String =
                "16.4.2-pre.38-kotlin-1.2.60" // available: milestone=16.5.0-pre.54-kotlin-1.2.70

        const val kotlin_react_router_dom: String =
                "4.3.1-pre.38-kotlin-1.2.60" // available: milestone=4.3.1-pre.54-kotlin-1.2.70

        const val kotlin_scripting_compiler_embeddable: String =
                "1.2.60" // available: milestone=1.3.20-dev-671

        const val kotlin_stdlib_common: String = "1.2.60" // available: milestone=1.3.20-dev-671

        const val kotlin_stdlib_jdk7: String = "1.2.60" // available: milestone=1.3.20-dev-671

        const val kotlin_stdlib_jdk8: String = "1.2.60" // available: milestone=1.3.20-dev-671

        const val kotlin_stdlib_js: String = "1.2.60" // available: milestone=1.3.20-dev-671

        const val kotlin_test: String = "1.2.60" // available: milestone=1.3.20-dev-671

        const val kotlin_test_annotations_common: String =
                "1.2.60" // available: milestone=1.3.20-dev-671

        const val kotlin_test_common: String = "1.2.60" // available: milestone=1.3.20-dev-671

        const val kotlin_test_js: String = "1.2.60" // available: milestone=1.3.20-dev-671

        const val kotlin_test_junit: String = "1.2.60" // available: milestone=1.3.20-dev-671

        const val kotlinandroidviewbindings: String = "0.10" // available: milestone=0.12

        const val kotlinx_coroutines_core: String = "0.24.0" // available: milestone=0.30.1

        const val kotlinx_coroutines_core_js: String = "0.24.0" // available: milestone=0.30.1

        const val kotlinx_coroutines_core_native: String = "0.24.0" 
                /* error: Could not resolve org.jetbrains.kotlinx:kotlinx-coroutines-core-native:+. 
                .... */

        const val kotlinx_coroutines_javafx: String = "0.16" // available: milestone=0.30.1

        const val kotlinx_gradle_serialization_plugin: String =
                "0.6.1" // available: milestone=0.7.0-eap-1

        const val kotlinx_html_js: String = "0.6.9" // available: milestone=0.6.11

        const val kotlinx_serialization_runtime: String = "0.6.1" // available: milestone=0.8.1-rc13

        const val kotlinx_serialization_runtime_js: String =
                "0.6.1" // available: milestone=0.8.1-rc13

        const val ktor_gson: String = "0.9.0" // available: milestone=0.9.6-alpha-1-rc13

        const val ktor_server_netty: String = "0.9.0" // available: milestone=0.9.6-alpha-1-rc13

        const val lint_gradle: String = "26.1.4" // available: milestone=26.3.0-alpha13

        const val logback_classic: String = "1.2.3" // available: milestone=1.3.0-alpha4

        const val logging_interceptor: String = "3.6.0" // available: milestone=3.11.0

        const val mockk: String = "1.7.2" // available: milestone=1.8.9

        const val multidex: String = "1.0.2" // available: milestone=1.0.3

        const val multidex_instrumentation: String = "1.0.2" // available: milestone=1.0.3

        const val okhttp: String = "3.6.0" // available: milestone=3.11.0

        const val preferenceholder: String = "1.51" // available: milestone=1.52-beta.5

        const val preferenceholder_gson_serializer: String =
                "1.51" // available: milestone=1.52-beta.5

        const val recyclerview_v7: String = "27.0.1" // available: milestone=28.0.0

        const val retrofit: String = "2.3.0" // available: milestone=2.4.0

        const val retrofit2_kotlin_coroutines_experimental_adapter: String = "1.0.0" // up-to-date

        const val rome: String = "1.9.0" // available: milestone=1.11.0

        const val sendgrid_java: String = "3.0.9" // available: milestone=4.2.1

        const val shadow: String = "2.0.1" // available: milestone=4.0.1

        const val squash: String = "0.2.3" // available: milestone=0.2.4

        const val squash_h2: String = "0.2.3" // available: milestone=0.2.4

        const val squash_postgres: String = "0.2.3" // available: milestone=0.2.4

        const val tornadofx: String = "1.7.13-SNAPSHOT" // available: milestone=1.7.17

        const val traynotification: String = "446c33b60c" 
                /* error: Could not find any matches for com.github.PlusHaze:TrayNotification:+ as no versions of com.github.PlusHaze:TrayNotification are available.
                Searched in the following locations:
                    http://dl.bintray.com/kotlin/kotlin-eap-1.2/com/github/PlusHaze/TrayNotification/maven-metadata.xml
                    https://kotlin.bintray.com/kotlinx/com/github/PlusHaze/TrayNotification/maven-metadata.xml 
                .... */

        const val wear: String = "27.0.1" // available: milestone=28.0.0
    }

    object Gradle {
        const val runningVersion: String = "4.7"

        const val currentVersion: String = "4.10.2"

        const val nightlyVersion: String = "5.0-20181002235907+0000"

        const val releaseCandidate: String = ""
    }
}
