# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kotlin Academy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kotlin Academy
	pod 'Alamofire'
    pod 'SDWebImage'
    pod 'AFNetworking', '~>3.0'
    pod 'SVProgressHUD'
    pod 'Reusable'

end
